# Generated by Django 3.2.25 on 2026-07-23 15:17

import action_education_training.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kolibriauth', '0035_facilitydataset_picture_password_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('channel_id', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('date_updated', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_trainings', to='kolibriauth.facility')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_trainings_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('start_datetime', kolibri.core.fields.DateTimeTzField()),
                ('end_datetime', kolibri.core.fields.DateTimeTzField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('date_updated', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_sessions_as_trainer', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='action_education_training.training')),
            ],
            options={
                'ordering': ('start_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('date_enrolled', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='active', max_length=20)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_enrollments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='action_education_training.trainingsession')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='action_education_training.training')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('issued_at', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('criteria_met', models.TextField(blank=True, default='')),
                ('printable_payload', models.TextField(blank=True, default='')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_certificates', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='action_education_training.training')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('date_recorded', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('date_updated', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_attendances', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_attendances_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='action_education_training.trainingsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('training', 'learner'), name='ae_enrollment_unique_training_learner'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('learner', 'training'), name='ae_certificate_unique_learner_training'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('session', 'learner'), name='ae_attendance_unique_session_learner'),
        ),
    ]
