# Generated by Django 3.2.25 on 2026-07-24 17:10

import action_education_training.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action_education_training', '0001_initial_training_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=127)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(max_length=512, upload_to=action_education_training.models.training_resource_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='action_education_training.training')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_training_resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'date_created'),
            },
        ),
    ]
