# Generated by Django 3.2.25 on 2026-09-30 00:30

import action_education_training.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action_education_training', '0002_training_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Final exam')], default='quiz', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('pass_percent', models.PositiveSmallIntegerField(default=50)),
                ('max_attempts', models.PositiveSmallIntegerField(default=0)),
                ('show_answers', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('date_created', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now, editable=False)),
                ('date_updated', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ae_quizzes_created', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='action_education_training.training')),
            ],
            options={
                'ordering': ('sort_order', 'date_created'),
            },
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingresource',
            name='file',
            field=models.FileField(blank=True, max_length=512, upload_to=action_education_training.models.training_resource_upload_to),
        ),
        migrations.AlterField(
            model_name='trainingresource',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('archive', 'Archive'), ('link', 'Link'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingresource',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingresource',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('first_viewed', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('last_viewed', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_resource_views', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='action_education_training.trainingresource')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('kind', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('true_false', 'True or false')], default='single', max_length=20)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='action_education_training.quiz')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='action_education_training.quizquestion')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.CharField(default=action_education_training.models._uuid_str, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('answers', kolibri.core.fields.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('date_submitted', kolibri.core.fields.DateTimeTzField(default=kolibri.utils.time_utils.local_now)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='action_education_training.quiz')),
            ],
            options={
                'ordering': ('-date_submitted',),
            },
        ),
        migrations.AddConstraint(
            model_name='resourceview',
            constraint=models.UniqueConstraint(fields=('resource', 'learner'), name='ae_resource_view_unique_resource_learner'),
        ),
    ]
